### PR TITLE
Update CI scripts

### PR DESCRIPTION
**Pull request by navidshaikh**
- [x] Add github workflows
- [x] Add .codecov.yaml config
- [x] Remove scripts/test-infra
- [x] Add hack scripts
- [x] Setup serving and eventing and update test scripts to run e2e

### CODE REVIEW

**Comment by navidshaikh** [comment]
/cc @zhanggbj This is ready to merge, now e2e tests are being run as well. Note that I've pinned serving/eventing versions to v0.19.x, update it as required.

There is another part remaining to wire `/hack/update-codegen.sh` with `./hac/build.sh` where I am constantly getting 
```
Error: one or more libraries have an incompatible/unknown license: map["unknown":["knative.dev/kn-plugin-admin/pkg" "knative.dev/kn-plugin-admin/pkg/command" "knative.dev/kn-plugin-admin/pkg/command/utils" "knative.dev/kn-plugin-admin/pkg/command/autoscaling" "knative.dev/kn-plugin-admin/pkg/command/domain" "knative.dev/kn-plugin-admin/pkg/command/profiling" "knative.dev/kn-plugin-admin/pkg/command/registry" "knative.dev/kn-plugin-admin/core" "knative.dev/kn-plugin-admin/cmd" "knative.dev/kn-plugin-admin/pkg/testutil"]]
```
I will work on it part of separate PR, but configured set of jobs should be good enough to test the existing PRs and unblock merging.
cc: @rhuss

**Comment by navidshaikh** [comment]
> There is another part remaining to wire /hack/update-codegen.sh with ./hac/build.sh where I am constantly getting

This is fixed now, LICENSE was missing in the repo. Thanks to @chizhg for the hint!

**Review by zhanggbj — APPROVED** [review]

**Review by zhanggbj — APPROVED** [review]

**Comment by zhanggbj** [comment]
/lgtm
Thanks @navidshaikh, looks great! Finally, we have tests running again!

**Pull request merged**
