### PR TITLE
Upgrade Go to 1.17

### PR DESCRIPTION
**Pull request by dsimansk**
Follow-up on Client go version upgrade.

# Changes

- :broom: Upgrade Go to 1.17

/cc @maximilien @rhuss @vyasgun

### CODE REVIEW

**Review by maximilien — APPROVED** [review]
/approve
/lgtm

**Review by maximilien — APPROVED** [review]
/ok-to-test

**Comment by maximilien** [comment]
Any chance to rebase @dsimansk ?

**Comment by dsimansk** [comment]
@maximilien done, sorry for the delay.

**Comment by dsimansk** [comment]
@maximilien or @vyasgun if you could take a look please. I've put auto-update PR on hold to avoid conflicts this time. :)

**Pull request merged**
