### PR TITLE
Preparing for 0.21 release

### PR DESCRIPTION
**Pull request by rhuss**
Includes update to go 1.15 and alignment of dependencies for kn 0.21

/hold until pkg-source is released (remove the last replace in go.mod then)

### CODE REVIEW

**Comment by dsimansk** [comment]
@googlebot I consent.

**Comment by dsimansk** [comment]
@rhuss one of the assert seems to failing due to different error format. Do you mind if I push one more commit?

**Review by maximilien — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by dsimansk** [comment]
@rhuss and test setup needs update too. 
https://github.com/knative-sandbox/kn-plugin-admin/blob/master/test/e2e-tests.sh#L25-L26

**Comment by rhuss** [comment]
> @rhuss one of the assert seems to failing due to different error format. Do you mind if I push one more commit?

go ahead !

**Review by maximilien — APPROVED** [review]
/lgtm

**Comment by rhuss** [comment]
@dsimansk sorry, forget to answer: If you can quickly fix the assertions, that would be great (and push then). Otherwise I can do it later, too

**Review by dsimansk — APPROVED** [review]

**Review by mattmoor — APPROVED** [review]

**Pull request merged**
